services:
  - type: web
    name: ticaret-analiz-sitesi
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
